namespace Marauder.Mini.Enums;

public enum Area : int
{
    None = 0,

    RogueEncampment = 1,
    BloodMoor,
    ColdPlains,
    StonyField,
    DarkWood,
    BlackMarsh,
    TamoeHighland,
    DenOfEvil,
    CaveLevel1,
    CaveLevel2,
    BurialGrounds,
    Crypt,
    Mausoleum,
    ForgottenTower,
    TowerCellarLevel1,
    TowerCellarLevel2,
    TowerCellarLevel3,
    TowerCellarLevel4,
    TowerCellarLevel5,
    MonasteryGate,
    OuterCloister,
    Barracks,
    JailLevel1,
    JailLevel2,
    JailLevel3,
    InnerCloister,
    Cathedral,
    CatacombsLevel1,
    CatacombsLevel2,
    CatacombsLevel3,
    CatacombsLevel4,
    Tristram,
    MooMooFarm = 39,

    LutGholein = 40,
    RockyWaste,
    DryHills,
    FarOasis,
    LostCity,
    ValleyOfSnakes,
    CanyonOfTheMagi,
    SewersLevel1Act2,
    SewersLevel2Act2,
    SewersLevel3Act2,
    HaremLevel1,
    HaremLevel2,
    PalaceCellarLevel1,
    PalaceCellarLevel2,
    PalaceCellarLevel3,
    StonyTombLevel1,
    HallsOfTheDeadLevel1,
    HallsOfTheDeadLevel2,
    ClawViperTempleLevel1,
    StonyTombLevel2,
    HallsOfTheDeadLevel3,
    ClawViperTempleLevel2,
    MaggotLairLevel1,
    MaggotLairLevel2,
    MaggotLairLevel3,
    AncientTunnels,
    TalRashasTomb1,
	TalRashasTomb2,
	TalRashasTomb3,
	TalRashasTomb4,
	TalRashasTomb5,
    TalRashasTomb6,
    TalRashasTomb7,
    DurielsLair,
    ArcaneSanctuary = 74,

    KurastDocks = 75,
    SpiderForest,
    GreatMarsh,
    FlayerJungle,
    LowerKurast,
    KurastBazaar,
    UpperKurast,
    KurastCauseway,
    Travincal,
    SpiderCave,
    SpiderCavern,
    SwampyPitLevel1,
    SwampyPitLevel2,
    FlayerDungeonLevel1,
    FlayerDungeonLevel2,
    SwampyPitLevel3,
    FlayerDungeonLevel3,
    SewersLevel1Act3,
    SewersLevel2Act3,
    RuinedTemple,
    DisusedFane,
    ForgottenTemple,
    RuinedFane,
    DisusedReliquary,
    ForgottenReliquary,
    DuranceOfHateLevel1,
    DuranceOfHateLevel2,
    DuranceOfHateLevel3 = 102,

    ThePandemoniumFortress = 103,
    OuterSteppes,
    PlainsOfDespair,
    CityOfTheDamned,
    RiverOfFlame,
    ChaosSanctuary = 108,
    
    Harrogath = 109,
    BloodyFoothills,
    FrigidHighlands,
    ArreatPlateau,
    CrystallinePassage,
    FrozenRiver,
    GlacialTrail,
    DrifterCavern,
    FrozenTundra,
    TheAncientsWay,
    IcyCellar,
    ArreatSummit,
    NihlathaksTemple,
    HallsOfAnguish,
    HallsOfPain,
    HallsOfVaught,
    Abaddon,
    PitOfAcheron,
    InfernalPit,
    TheWorldStoneKeepLevel1,
    TheWorldStoneKeepLevel2,
    TheWorldStoneKeepLevel3,
    ThroneOfDestruction,
    TheWorldstoneChamber = 132,

    MatronsDen,
    ForgottenSands,
    FurnaceOfPain,
    UberTristram,
    MapsAncientTemple,
    MapsDesecratedTemple,
    MapsFrigidPlateau,
    MapsInfernalTrial,
    MapsRuinedCitadel
}
